#Configuration for mongoid to connect to the mongodb server

development:
  clients:
    default:
      database: test      
      hosts:
        - ec2-54-149-63-164.us-west-2.compute.amazonaws.com:27017

production:
  clients:
    default:
      database: admin      
      hosts:
        - ec2-54-149-63-164.us-west-2.compute.amazonaws.com:27017
  
